# Change these first
owner: urvana # Your GitHub organization or username, where this repository lives
repo: urvana-upptime # The name of this repository

sites:
  - name: API Health
    url: https://urvana.net/api/health
    maxResponseTime: 3000
  - name: Landing page
    url: https://urvana.net
    maxResponseTime: 5000
  - name: Supabase bucket
    url: https://adxcdfekysrkrquykrdy.supabase.co/storage/v1/object/public/assets/logo.png
    maxResponseTime: 3000

assignees: # Users to assign downtime issues (optional)
  - lopezjurip
  - oisangui

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /urvana-upptime
  logoUrl: https://adxcdfekysrkrquykrdy.supabase.co/storage/v1/object/public/assets/logo.png
  name: URVANA
  introTitle: "**[URVANA](https://urvana.net?ref=status)** — sistema operativo para el desarrollo inmobiliario"
  introMessage: "Página es status abierta."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Twitter
      href: https://twitter.com/urvana_net
    - title: Inicio
      href: https://urvana.net?ref=status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
